# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0002_auto_20180215_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='backgroundColor',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
