# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0003_auto_20180215_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='end',
        ),
        migrations.RemoveField(
            model_name='events',
            name='start',
        ),
        migrations.AddField(
            model_name='events',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
