# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0005_meetpartner_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetpartner',
            name='text',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='memorandums',
            name='text',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='quotesday',
            name='text',
            field=models.CharField(max_length=2000),
        ),
    ]
