# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0006_auto_20180219_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetpartner',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='memorandums',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quotesday',
            name='text',
            field=models.TextField(),
        ),
    ]
