# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0007_auto_20180219_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birthdays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('allDay', models.BooleanField(default=True)),
                ('start_date', models.DateField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('backgroundColor', models.CharField(default='#1b9200', max_length=15, null=True)),
            ],
        ),
    ]
