# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0009_auto_20180220_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='backgroundColor',
            field=models.CharField(default='#1b9200', editable=False, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='end_date',
            field=models.DateField(auto_now=True),
        ),
    ]
