# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0011_auto_20180220_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
