# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0014_meetpartner_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='thumb',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='welcome',
            name='thumb',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
