# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0015_auto_20180222_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnhorabuenaKids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('sexo', models.CharField(choices=[('B', 'Ni\xf1o'), ('G', 'Ni\xf1a')], max_length=2)),
                ('picture', models.ImageField(null=True, upload_to='photos/%Y/%m/%d')),
                ('thumb', models.ImageField(null=True, upload_to='photos/%Y/%m/%d')),
                ('text', models.TextField()),
            ],
        ),
    ]
