# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0016_enhorabuenakids'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnhorabuenaKids',
            new_name='EnhorabuenaKid',
        ),
    ]
