# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0017_auto_20180222_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enhorabuenakid',
            name='thumb',
        ),
    ]
