# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0020_auto_20180301_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enhorabuenakid',
            name='picture',
            field=models.ImageField(upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='enhorabuenakid',
            name='thumb',
            field=models.ImageField(upload_to='photos/%Y/%m/%d'),
        ),
    ]
