# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 19:55
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0027_auto_20180306_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='allDay',
            field=models.BooleanField(default=True, verbose_name='Todo el dia'),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='backgroundColor',
            field=models.CharField(default='#1b9200', editable=False, max_length=15, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='department',
            field=models.CharField(max_length=80, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='end_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Fecha de termino'),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='end_time',
            field=models.TimeField(auto_now=True, verbose_name='Hora de termino'),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='start_time',
            field=models.TimeField(auto_now=True, verbose_name='Hora de inicio'),
        ),
        migrations.AlterField(
            model_name='enhorabuenakid',
            name='picture',
            field=models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='enhorabuenakid',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='enhorabuenakid',
            name='thumb',
            field=models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Imagen de fondo'),
        ),
        migrations.AlterField(
            model_name='enhorabuenakid',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='allDay',
            field=models.BooleanField(verbose_name='Todo el dia'),
        ),
        migrations.AlterField(
            model_name='event',
            name='backgroundColor',
            field=models.CharField(max_length=15, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Detalles'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(null=True, verbose_name='Fecha de termino'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='Hora de termino'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='Hora de inicio'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=80, verbose_name='titulo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.CharField(default='#modal', editable=False, max_length=80),
        ),
        migrations.AlterField(
            model_name='meetpartner',
            name='department',
            field=models.CharField(max_length=30, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='meetpartner',
            name='picture',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='meetpartner',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='meetpartner',
            name='thumb',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d', verbose_name='Imagen de fondo'),
        ),
        migrations.AlterField(
            model_name='meetpartner',
            name='title',
            field=models.CharField(max_length=30, null=True, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='memorandum',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='memorandum',
            name='title',
            field=models.CharField(max_length=30, null=True, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='picture',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='thumb',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d', verbose_name='Imagen de fondo'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='title',
            field=models.CharField(max_length=30, null=True, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='welcome',
            name='picture',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='welcome',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='welcome',
            name='thumb',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d', verbose_name='Imagen de fondo'),
        ),
        migrations.AlterField(
            model_name='welcome',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Titulo'),
        ),
    ]
