# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 14:11
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0028_auto_20180309_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='MournfulNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Titulo')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Texto')),
            ],
            options={
                'verbose_name': 'Nota luctuosa',
                'verbose_name_plural': 'Notas luctuosas',
            },
        ),
        migrations.AlterModelOptions(
            name='birthday',
            options={'verbose_name': 'Cumplea\xf1o', 'verbose_name_plural': 'Cumplea\xf1os'},
        ),
        migrations.AlterModelOptions(
            name='enhorabuenakid',
            options={'verbose_name': 'Enhorabuena ni\xf1o', 'verbose_name_plural': 'Enhorabuena ni\xf1os'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='meetpartner',
            options={'verbose_name': 'Tu compa\xf1ero Delta', 'verbose_name_plural': 'Conoce a tu compa\xf1ero Delta'},
        ),
        migrations.AlterModelOptions(
            name='memorandum',
            options={'verbose_name': 'Memo', 'verbose_name_plural': 'Memorandums'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name': 'Promocion - traslado', 'verbose_name_plural': 'Promociones - traslados'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name': 'Frase', 'verbose_name_plural': 'Frases'},
        ),
        migrations.AlterModelOptions(
            name='welcome',
            options={'verbose_name': 'Bienvenida', 'verbose_name_plural': 'Bienvenidas'},
        ),
    ]
