# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 17:03
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0029_auto_20180410_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorandum',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Descripcion'),
        ),
    ]
