# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-10 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0031_memorandum_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorandum',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
