# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-11 20:24
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0032_auto_20180410_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Detalles'),
        ),
    ]
