# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-25 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0034_auto_20180411_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorandum',
            name='color',
            field=models.CharField(default='teal', max_length=15, verbose_name='Color'),
        ),
    ]
