# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-03 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0035_memorandum_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorandum',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Color'),
        ),
    ]
