# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-15 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0037_auto_20180503_1217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnhorabuenaKid',
        ),
        migrations.DeleteModel(
            name='MeetPartner',
        ),
        migrations.DeleteModel(
            name='MournfulNote',
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
        migrations.DeleteModel(
            name='Welcome',
        ),
        migrations.RemoveField(
            model_name='memorandum',
            name='color',
        ),
        migrations.AddField(
            model_name='memorandum',
            name='picture',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='memorandum',
            name='section',
            field=models.CharField(choices=[('memo', 'Memorandum'), ('welcome', 'Bienvenida'), ('promotion', 'Promocion'), ('meet', 'Conoce compa\xf1ero'), ('mournful', 'Nota Luctuosa'), ('birthboy', 'Nacimiento/Ni\xf1o'), ('birthgirl', 'Nacimiento/Ni\xf1a')], default='memo', max_length=30, verbose_name='Tipo de publicacion'),
        ),
    ]
