# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-16 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0038_auto_20180615_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorandum',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Imagen'),
        ),
    ]
