# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-19 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0040_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorandum',
            name='color',
            field=models.CharField(default='#009688', max_length=300),
        ),
        migrations.AddField(
            model_name='memorandum',
            name='slug',
            field=models.SlugField(default='test', max_length=300, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
