# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-01 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0042_auto_20180726_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorandum',
            name='section',
            field=models.CharField(choices=[('memo', 'Memorandum'), ('welcome', 'Bienvenida'), ('promotion', 'Promocion'), ('meet', 'Conoce compa\xf1ero'), ('mournful', 'Nota Luctuosa'), ('accompli', 'Noti Cumplimiento'), ('notes', 'Notas de Interes'), ('birthboy', 'Nacimiento/Ni\xf1o'), ('birthgirl', 'Nacimiento/Ni\xf1a')], default='memo', max_length=30, verbose_name='Tipo de publicacion'),
        ),
    ]
