# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-20 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0044_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Sugerencia', 'verbose_name_plural': 'Sugerencias'},
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('lexussalon', 'Salon de Entrenamiento - Lexus'), ('conferencesalon', 'Salon de Conferencia - Administrativo')], default='lexussalon', max_length=30, verbose_name='Lugar'),
        ),
    ]
