# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-21 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0045_auto_20180920_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('lexussalon', 'Sal\xf3n de Entrenamiento - Lexus'), ('conferencesalon', 'Sal\xf3n de Conferencia - Administrativo')], default='lexussalon', max_length=30, verbose_name='Lugar'),
        ),
    ]
