# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-12 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0046_auto_20180921_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('Sal\xf3n de Entrenamiento - Lexus', 'Sal\xf3n de Entrenamiento - Lexus'), ('Sal\xf3n de Conferencia - Administrativo', 'Sal\xf3n de Conferencia - Administrativo')], default='lexussalon', max_length=30, verbose_name='Lugar'),
        ),
    ]
